### ISSUE TITLE
Consider using hashtags for specific terms

### ISSUE THREAD

**Issue by RaoOfPhysics** [clelange/cds_paper_bot#11]
General examples*, applicable to both:

- [\#Higgs](https://twitter.com/hashtag/Higgs)
- [\#13TeV](https://twitter.com/hashtag/13TeV)

CMS-[/ATLAS-]specific ones:

- [\#CMSPAS](https://twitter.com/hashtag/CMSPAS) for analysis summaries
- [\#CMSpaper](https://twitter.com/hashtag/CMSpaper) for papers
- [\#CMSSUS](https://twitter.com/hashtag/CMSpaper), at the start of the tweet, to define the PAG the document belongs to

---

\* \#SUSY, \#darkmatter etc. all appear to be used for non-physics cases, so be careful here.

**Comment by clelange** [comment]
Closed by https://github.com/clelange/cds_paper_bot/commit/e875076e0e90e05316404af22947651c889826c8

@RaoOfPhysics Feel free to reopen or create a new issue if you have further suggestions/comments.

**Comment by RaoOfPhysics** [comment]
Thanks for taking on board the suggestion. :)
